name: Node.js CI/CD
on:
  push:
    branches: [master]
jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '10.x'
      - name: install dependies
        run: npm install
      - name: for running
        run: npm run start
      
