name: CI/CD Pipeline for hello

on:
  push:
    branches: 
        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build nodejs application
        run: npm run 

      - name: Test nodejs application
        run: npm test  
      - name: for running nodejs
        run: npm run start
       
